### ISSUE TITLE
Verify slow in reply mode

### ISSUE THREAD

**Issue by gicking** [gicking/stm8gal#20]
Reading out and/or verifying data in "UART reply mode" is very slow over 2-wire interface. This is caused by a few ms latency for each byte which must be echoed by the PC. Using a FT232R, reading back 14kB takes ~5min

**Comment by gicking** [comment]
Fixed via v1.4.2 and CRC32 verify option (32kB in 2.4s, 128kB in 4.9s). To use CRC32 check use option "-V 1"

**Comment by MarkStokes71** [comment]
Thank you, this should prove very valuable!

**Comment by gicking** [comment]
Update v1.4.3 fixes an address conflict with STM8L low-density BL v1.0. RAM code now starts at 0x210. For technical details see https://github.com/gicking/stm8gal/blob/master/verify_CRC32/README.md
