### ISSUE TITLE
Pre-built windows executable please :)

### ISSUE THREAD

**Issue by gfmoore** [gicking/stm8gal#22]
I hope you are still around :)

I am trying to learn how to use an STM8S with a STM8S-discovery board and I can flash using STVP, but I'd like to incorporate a command line flash into my VS Code (tasks.json calling the Makefile flash option I wrote)

I have gcc installed, but I don't want to have to start installing mingw etc.

I don't suppose you have a pre-built win10 version available for me to use do you? 

Gordon

**Comment by gicking** [comment]
hi gfmoore,

yep, still around and kicking...  ;-)

You can find pre-compiled binaries under [releases](https://github.com/gicking/stm8gal/releases). Hope it works for you!

Georg

**Comment by gfmoore** [comment]
Great, thanks, missed that :)

**Comment by gicking** [comment]
:-)
