### ISSUE TITLE
[question] where is the BSL_activate codes?

### ISSUE THREAD

**Issue by cjacker** [gicking/stm8gal#32]
I noticed BSL_activate codes removed after commit 67f8c398782a4ec4c51989cb6a3768935e3ca1c8 "migrate to PlatformIO / VSCode file structure". And where it is now?

**Comment by gicking** [comment]
hi cjacker,
apparently I accidentally deleted "BSL_activate". I just uploaded it again, and you can now find it under "tools". Have fun! gicking
