### ISSUE TITLE
Build for OSX and for Windows fails due to missing SPI device

### ISSUE THREAD

**Issue by tenbaht** [gicking/stm8gal#5]
Compilation on OSX and on Windows fails for two reasons:

- the Makefile tries to compile spi_spidev_comm.c (shouldn't be compiled at all on these platforms)
- the flag `-DUSE_SPIDEV` is automatically set for OSX.

An easy workaround is to delete `spi_spidev_comm.c` from the list in `SOURCES` in the Makefile and start the compilation with this call: `make OS=Win`. Yes, even on OSX it needs `OS=Win`.

**Comment by gicking** [comment]
yep, stupid mistake - just tried to be too clever! Anyway, I have now made both `SPIdev` and `WiringPi` (RasPi only) optional in the Makefile. Just comment them in as required.

Please let me know if this is ok for you. Thanks in advance!
